version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "${ZOOKEEPER_EXT_PORT}:2181"
  kafka:
    build: .
    ports:
      - "${KAFKA_EXT_PORT}:9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: ${IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test,all,cameras,thermometers"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
